/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package irfan_18042024;

/**
 *
 * @author Lab-J2-01
 */
public class formgaji extends javax.swing.JFrame {

    /**
     * Creates new form formgaji
     */
    public formgaji() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        PanelJudul = new javax.swing.JLabel();
        Panelidentitas = new javax.swing.JPanel();
        Identitas = new javax.swing.JLabel();
        LabelNama = new javax.swing.JLabel();
        LabelNIK = new javax.swing.JLabel();
        LabelGolongan = new javax.swing.JLabel();
        Jamkerja = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtNIK = new javax.swing.JTextField();
        txtJamkerja = new javax.swing.JTextField();
        CbGol = new javax.swing.JComboBox<>();
        ButtonHitung = new javax.swing.JButton();
        ButtonDesk = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Rinciangaji = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LabelGajiPokok = new javax.swing.JLabel();
        LabelUpah = new javax.swing.JLabel();
        txtGapok = new javax.swing.JTextField();
        txtUpah = new javax.swing.JTextField();
        LabelTotalUpah = new javax.swing.JLabel();
        LabelTotalGaji = new javax.swing.JLabel();
        txtTotalUP = new javax.swing.JTextField();
        txtTotalGaji = new javax.swing.JTextField();
        Panelketerangan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtAreaKet = new javax.swing.JTextArea();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        PanelJudul.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PanelJudul.setText("GAJI KARYAWAN PT ABC");
        PanelJudul.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Panelidentitas.setBackground(new java.awt.Color(153, 204, 255));
        Panelidentitas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Identitas.setText("IDENTITAS");

        LabelNama.setText("NAMA");

        LabelNIK.setText("NIK");

        LabelGolongan.setText("Golongan");

        Jamkerja.setText("Jam Kerja");

        txtNIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNIKActionPerformed(evt);
            }
        });

        CbGol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIHAN GOLONGAN", "Golongan 1", "Golongan 2", "Golongan 3", "Golongan 4", " " }));
        CbGol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbGolActionPerformed(evt);
            }
        });

        ButtonHitung.setText("Hitung");
        ButtonHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHitungActionPerformed(evt);
            }
        });

        ButtonDesk.setText("Deskripsi");
        ButtonDesk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeskActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        javax.swing.GroupLayout PanelidentitasLayout = new javax.swing.GroupLayout(Panelidentitas);
        Panelidentitas.setLayout(PanelidentitasLayout);
        PanelidentitasLayout.setHorizontalGroup(
            PanelidentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelidentitasLayout.createSequentialGroup()
                .addGroup(PanelidentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelidentitasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Identitas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelidentitasLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(PanelidentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LabelGolongan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(LabelNIK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelNama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Jamkerja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelidentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnama)
                            .addComponent(txtNIK)
                            .addGroup(PanelidentitasLayout.createSequentialGroup()
                                .addGroup(PanelidentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtJamkerja, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CbGol, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButtonHitung))
                            .addGroup(PanelidentitasLayout.createSequentialGroup()
                                .addComponent(ButtonDesk)
                                .addGap(34, 34, 34)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(jButton3)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelidentitasLayout.setVerticalGroup(
            PanelidentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelidentitasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Identitas)
                .addGap(18, 18, 18)
                .addGroup(PanelidentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNama)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelidentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNIK)
                    .addComponent(txtNIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelidentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelGolongan)
                    .addComponent(CbGol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelidentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jamkerja)
                    .addComponent(txtJamkerja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonHitung))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(PanelidentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonDesk)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(28, 28, 28))
        );

        Rinciangaji.setBackground(new java.awt.Color(51, 204, 255));

        jLabel1.setText("RINCIAN GAJI");

        LabelGajiPokok.setText("GP");

        LabelUpah.setText("UP");

        txtUpah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpahActionPerformed(evt);
            }
        });

        LabelTotalUpah.setText("TotalUP");

        LabelTotalGaji.setText("TotalGaji");

        txtTotalUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalUPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RinciangajiLayout = new javax.swing.GroupLayout(Rinciangaji);
        Rinciangaji.setLayout(RinciangajiLayout);
        RinciangajiLayout.setHorizontalGroup(
            RinciangajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RinciangajiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RinciangajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RinciangajiLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(RinciangajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RinciangajiLayout.createSequentialGroup()
                                .addComponent(LabelTotalUpah)
                                .addGap(35, 35, 35))
                            .addGroup(RinciangajiLayout.createSequentialGroup()
                                .addComponent(LabelTotalGaji)
                                .addGap(30, 30, 30)))
                        .addGroup(RinciangajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTotalGaji, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(txtTotalUP)))
                    .addGroup(RinciangajiLayout.createSequentialGroup()
                        .addGroup(RinciangajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelUpah)
                            .addComponent(LabelGajiPokok)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(RinciangajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGapok, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUpah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RinciangajiLayout.setVerticalGroup(
            RinciangajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RinciangajiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RinciangajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGapok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelGajiPokok))
                .addGap(18, 18, 18)
                .addGroup(RinciangajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RinciangajiLayout.createSequentialGroup()
                        .addGroup(RinciangajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelUpah)
                            .addComponent(txtUpah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(RinciangajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelTotalUpah)
                            .addComponent(txtTotalUP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(LabelTotalGaji))
                    .addComponent(txtTotalGaji, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panelketerangan.setBackground(new java.awt.Color(102, 204, 255));

        jLabel2.setText("KETERANGAN");

        TxtAreaKet.setColumns(20);
        TxtAreaKet.setRows(5);
        jScrollPane1.setViewportView(TxtAreaKet);

        javax.swing.GroupLayout PanelketeranganLayout = new javax.swing.GroupLayout(Panelketerangan);
        Panelketerangan.setLayout(PanelketeranganLayout);
        PanelketeranganLayout.setHorizontalGroup(
            PanelketeranganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelketeranganLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelketeranganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addGroup(PanelketeranganLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelketeranganLayout.setVerticalGroup(
            PanelketeranganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelketeranganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panelidentitas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(PanelJudul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Rinciangaji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Panelketerangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelJudul))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panelidentitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Rinciangaji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panelketerangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Panelidentitas.getAccessibleContext().setAccessibleName("");
        Panelidentitas.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNIKActionPerformed

    private void CbGolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbGolActionPerformed
        // TODO add your handling code here:
        int  gp=0; 
        int up=0;
        switch(CbGol.getSelectedIndex())
        {
            case 1 : gp=1000000; up=5000;break;
            case 2 : gp=1500000; up=7000;break;
            case 3 : gp=2000000; up=10000;break;
            case 4 : gp=2500000; up=12500;break;
        }
        txtGapok.setText(String.valueOf(gp));
        txtUpah.setText(String.valueOf(up));
    }//GEN-LAST:event_CbGolActionPerformed

    private void txtUpahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpahActionPerformed

    private void ButtonHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHitungActionPerformed
        // TODO add your handling code here:
        int tu=0;
        int jk=Integer.parseInt(txtJamkerja.getText());
        tu= Integer.parseInt(txtUpah.getText())*jk;
        txtTotalUP.setText(""+tu);
        int totalgaji= Integer.parseInt(txtGapok.getText())+tu;
        txtTotalGaji.setText(""+totalgaji);
        
    }//GEN-LAST:event_ButtonHitungActionPerformed

    private void txtTotalUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalUPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalUPActionPerformed

    private void ButtonDeskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeskActionPerformed
        String NAMA,NIK,Keterangan;
        NAMA = txtnama.getText();
        NIK = txtNIK.getText();
        int tg=Integer.parseInt(txtTotalGaji.getText());
        Keterangan = "Data pegawai \n Nama= "+NAMA+
                     "\n NIK = "+NIK+
                     "\n Total Gaji = " +tg;
        TxtAreaKet.setText(Keterangan);
        
    }//GEN-LAST:event_ButtonDeskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formgaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formgaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formgaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formgaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formgaji().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDesk;
    private javax.swing.JButton ButtonHitung;
    private javax.swing.JComboBox<String> CbGol;
    private javax.swing.JLabel Identitas;
    private javax.swing.JLabel Jamkerja;
    private javax.swing.JLabel LabelGajiPokok;
    private javax.swing.JLabel LabelGolongan;
    private javax.swing.JLabel LabelNIK;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JLabel LabelTotalGaji;
    private javax.swing.JLabel LabelTotalUpah;
    private javax.swing.JLabel LabelUpah;
    private javax.swing.JLabel PanelJudul;
    private javax.swing.JPanel Panelidentitas;
    private javax.swing.JPanel Panelketerangan;
    private javax.swing.JPanel Rinciangaji;
    private javax.swing.JTextArea TxtAreaKet;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtGapok;
    private javax.swing.JTextField txtJamkerja;
    private javax.swing.JTextField txtNIK;
    private javax.swing.JTextField txtTotalGaji;
    private javax.swing.JTextField txtTotalUP;
    private javax.swing.JTextField txtUpah;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables
}
